/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Gopal Roy
 */
public class choose_decompression extends javax.swing.JFrame {

    /**
     * Creates new form choose_decompression
     */
    public choose_decompression() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXT = new javax.swing.JButton();
        png = new javax.swing.JButton();
        PDF = new javax.swing.JButton();
        mp4 = new javax.swing.JButton();
        JPG = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EXIT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(630, 280));
        setMinimumSize(new java.awt.Dimension(630, 280));
        setPreferredSize(new java.awt.Dimension(630, 280));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TXT.setBackground(new java.awt.Color(102, 255, 0));
        TXT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXT.setText("txt");
        TXT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTActionPerformed(evt);
            }
        });
        getContentPane().add(TXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 56, 70, 30));

        png.setBackground(new java.awt.Color(102, 255, 0));
        png.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        png.setText("png");
        png.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        png.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        png.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pngActionPerformed(evt);
            }
        });
        getContentPane().add(png, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 56, 80, 30));

        PDF.setBackground(new java.awt.Color(102, 255, 0));
        PDF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PDF.setText("pdf");
        PDF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFActionPerformed(evt);
            }
        });
        getContentPane().add(PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 56, 70, 30));

        mp4.setBackground(new java.awt.Color(102, 255, 0));
        mp4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mp4.setText("mp4");
        mp4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mp4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mp4ActionPerformed(evt);
            }
        });
        getContentPane().add(mp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 56, 80, 30));

        JPG.setBackground(new java.awt.Color(102, 255, 0));
        JPG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JPG.setText("jpg");
        JPG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPGActionPerformed(evt);
            }
        });
        getContentPane().add(JPG, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 56, 70, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setText("Choose in which format you want to Decompress");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        EXIT.setBackground(new java.awt.Color(255, 51, 0));
        EXIT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EXIT.setText("Exit");
        EXIT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EXIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 166, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/istockphoto-1368237807-170667a.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTActionPerformed
        // TODO add your handling code here:
                JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filePath = file.getAbsolutePath();
         try{
                    Decompress_algos.gzDecompress(file);
                }
                catch(Exception excp){
                    JOptionPane.showMessageDialog(null, excp.toString());
                }
          JOptionPane.showMessageDialog(null,"It is done");
    }//GEN-LAST:event_TXTActionPerformed

    private void pngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pngActionPerformed
        // TODO add your handling code here:
                        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filePath = file.getAbsolutePath();
         try{
                    Decompress_algos.gzDecompresspng(file);
                }
                catch(Exception excp){
                    JOptionPane.showMessageDialog(null, excp.toString());
                }
          JOptionPane.showMessageDialog(null,"It is done");
    }//GEN-LAST:event_pngActionPerformed

    private void PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFActionPerformed
        // TODO add your handling code here:
                        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filePath = file.getAbsolutePath();
         try{
                    Decompress_algos.gzDecompresspdf(file);
                }
                catch(Exception excp){
                    JOptionPane.showMessageDialog(null, excp.toString());
                }
          JOptionPane.showMessageDialog(null,"It is done");
    }//GEN-LAST:event_PDFActionPerformed

    private void mp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mp4ActionPerformed
        // TODO add your handling code here:
                        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filePath = file.getAbsolutePath();
         try{
                    Decompress_algos.gzDecompressmp4(file);
                }
                catch(Exception excp){
                    JOptionPane.showMessageDialog(null, excp.toString());
                }
          JOptionPane.showMessageDialog(null,"It is done");
    }//GEN-LAST:event_mp4ActionPerformed

    private void JPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPGActionPerformed
        // TODO add your handling code here:
                        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filePath = file.getAbsolutePath();
         try{
                    Decompress_algos.gzDecompressjpg(file);
                }
                catch(Exception excp){
                    JOptionPane.showMessageDialog(null, excp.toString());
                }
          JOptionPane.showMessageDialog(null,"It is done");
    }//GEN-LAST:event_JPGActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:\
          int res = JOptionPane.showConfirmDialog(null,"Are you sure that you want to exit");
                if(res ==0){
                    setVisible(false);
                    
                }
                Home frame = new Home();
                frame.setVisible(true);
    }//GEN-LAST:event_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choose_decompression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choose_decompression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choose_decompression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choose_decompression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choose_decompression().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JButton JPG;
    private javax.swing.JButton PDF;
    private javax.swing.JButton TXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mp4;
    private javax.swing.JButton png;
    // End of variables declaration//GEN-END:variables
}
