/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Gopal Roy
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        COMPRESS_IN_TO_GZ = new javax.swing.JButton();
        DECOMPRESS_GZ = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(627, 278));
        setMinimumSize(new java.awt.Dimension(627, 278));
        setPreferredSize(new java.awt.Dimension(627, 278));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        COMPRESS_IN_TO_GZ.setBackground(new java.awt.Color(51, 255, 51));
        COMPRESS_IN_TO_GZ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        COMPRESS_IN_TO_GZ.setText("Compress ");
        COMPRESS_IN_TO_GZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMPRESS_IN_TO_GZActionPerformed(evt);
            }
        });
        getContentPane().add(COMPRESS_IN_TO_GZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 150, 40));

        DECOMPRESS_GZ.setBackground(new java.awt.Color(51, 255, 51));
        DECOMPRESS_GZ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DECOMPRESS_GZ.setText("Decompress ");
        DECOMPRESS_GZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DECOMPRESS_GZActionPerformed(evt);
            }
        });
        getContentPane().add(DECOMPRESS_GZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 140, 40));

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/istockphoto-1368237807-170667a.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void COMPRESS_IN_TO_GZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMPRESS_IN_TO_GZActionPerformed
        // TODO add your handling code here:
        choose_compressions frame = new choose_compressions();
        frame.setVisible(true);
        
    }//GEN-LAST:event_COMPRESS_IN_TO_GZActionPerformed

    private void DECOMPRESS_GZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DECOMPRESS_GZActionPerformed
        // TODO add your handling code here:
        choose_decompression frame = new choose_decompression();
        frame.setVisible(true);
    }//GEN-LAST:event_DECOMPRESS_GZActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          int res = JOptionPane.showConfirmDialog(null,"Are you sure that you want to exit");
                if(res ==0){
                    setVisible(false);
                    
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton COMPRESS_IN_TO_GZ;
    private javax.swing.JButton DECOMPRESS_GZ;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
